chore: iteration to configuration pages
stateful/docs.runme.dev pull request #305
Opened 2024-02-14 18:12 UTC by edeediong

2024-02-15 20:13 UTC, sourishkrout requested changes
See comments please.

2024-02-15 20:13 UTC, sourishkrout commented on docs/configuration/cell-level.md
> +```sh {"id":"01HPPF1PRAK846NR2H1CW86XVQ"}
somethings not right here

2024-02-15 20:13 UTC, sourishkrout commented on docs/configuration/cell-level.md
> +```sh {"id":"01HPPF1PRAWK6WV432SB6KVF6G"}
also not right here either

2024-02-15 20:13 UTC, sourishkrout commented on docs/configuration/lifecycle-identity.md
>    version: v2.0
Starting with v3 it will no longer write the minor digit making this `version: v2`

2024-02-15 20:13 UTC, sourishkrout commented on docs/configuration/shebang.md
> +```sh {"id":"01HPPEWMR03X1RNX68H4G28T6A"}
should this say `js` instead of `sh`?

2024-02-15 20:13 UTC, sourishkrout commented on docs/configuration/shebang.md
> +```sh {"id":"01HPPEWMR0WHY93Q0MVFQ4YHS8"}
this should likely say `rb` instead of `sh`

2024-02-15 21:12 UTC, joseeantonior commented on docs/configuration/shebang.md
> +```sh {"id":"01HPPEWMR03X1RNX68H4G28T6A"}
Yup, that sounds right.

2024-02-15 21:14 UTC, joseeantonior commented
LGTM other than what @sourishkrout mentioned.

2024-02-16 03:07 UTC, sourishkrout approved these changes
👍 LGTM

2024-02-16 03:07 UTC, merged