docs: create how-runme-works subsection
stateful/docs.runme.dev pull request #309
Opened 2024-02-15 14:17 UTC by edeediong

2024-02-15 20:19 UTC, sourishkrout commented on docs/getting-started/faq.md
> +## **What is Runme Default editor in Vscode?**
`VS Code` brand spelling

2024-02-15 20:21 UTC, sourishkrout commented on docs/how-runme-works/VSCode.md
> +# Runme on Vscode
`VS Code` brand spelling

2024-02-15 20:24 UTC, sourishkrout requested changes
See comments please. Also, "How Runme Works" needs below "Getting Started" in the side navbar. It's out of place in 3rd place.

2024-02-15 20:24 UTC, sourishkrout commented on docs/how-runme-works/cli.md
The help text below is old

2024-02-15 21:10 UTC, joseeantonior requested changes
- "Using runme on a remote server with VSCode" let's capitalize Runme and add a space in VS Code. // Runme via SSH

2024-02-15 21:10 UTC, joseeantonior commented on docs/how-runme-works/index.md
> +Runme aims to deliver an excellent experience from the very beginning. To learn how to make the most out of our markdown docs. If you haven't already installed Runme, please complete the steps in [in
This line doesn't quite make sense to me. Please review and reword.

2024-02-15 21:15 UTC, joseeantonior commented
As a side-note, we should grep all of the appearances of `vscode` and `markdown` and make sure they are properly spelled.

2024-02-16 03:19 UTC, sourishkrout approved these changes
👍  LGTM

2024-02-16 03:23 UTC, merged