docs: add new page helm
stateful/docs.runme.dev pull request #356
Opened 2024-04-08 15:56 UTC by edeediong

2024-04-09 21:06 UTC, joseeantonior commented on docs/configuration/cellsection.md
> +- Now enable Stick Scroll by clicking on the “Enabled” checkbox.
We've been calling it "sticky scroll" but it mentions "Stick Scroll" here. We should standardize the use of the term to either "the Stick Scroll feature" or "sticky scroll".

2024-04-09 21:08 UTC, joseeantonior commented on docs/guide/helm.md
> +This guide demonstrates how to integrate Helm with Runme to automate processes and reduce repetitive tasks.
There, it's actually a package manager, and not an automation tool. We should definitely be explicit.

2024-04-10 13:35 UTC, sourishkrout requested changes
Please see comment about notebook, otherwise 👍 .

2024-04-15 12:06 UTC, edeediong commented on docs/configuration/cellsection.md
> +- Now enable Stick Scroll by clicking on the “Enabled” checkbox.
We are going to stick with "sticky scroll".

2024-04-15 12:07 UTC, merged